#!/usr/bin/env python

import sys, socket, select, time, json, random

class KVStore:
	# Timeout in milliseconds
	TIMEOUT = 500

	def __init__(self, id, replicas):
		# Instance ID number
		self.my_id = id
		# The ID numbers of all the other replicas
		self.replica_ids = replicas
		# The current election term across all replicas
		self.term = 0
		# Needs to be one of the following: follower, candidate, leader
		self.state = 'follower'

	def listen(self):
		# Connect to the network. All messages to/from other replicas and clients will
		# occur over this socket
		sock = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
		sock.connect(self.my_id)
		last = 0

		while True:
			ready = select.select([sock], [], [], 0.1)[0]

			if sock in ready:
				msg_raw = sock.recv(32768)

				if len(msg_raw) == 0: continue
				msg = json.loads(msg_raw)

				# For now, ignore get() and put() from clients
				if msg['type'] in ['get', 'put']:
					pass
					# print('type: ' + msg['type'])

				# Handle noop messages. This may be removed from your final implementation
				elif msg['type'] == 'noop':
					print '%s received a NOOP from %s' % (msg['dst'], msg['src'])

			clock = time.time()
			if clock-last > 2:
				# Send a no-op message to a random peer every two seconds, just for fun
				# You definitely want to remove this from your implementation
				msg = {'src': self.my_id, 'dst': random.choice(self.replica_ids), 'leader': 'FFFF', 'type': 'noop'}
				sock.send(json.dumps(msg))
				print '%s sending a NOOP to %s' % (msg['src'], msg['dst'])
				last = clock


if __name__ == "__main__":
	init_id = sys.argv[1]
	init_replica_ids = sys.argv[2:]

	db = KVStore(init_id, init_replica_ids)
